:source 'https://rubygems.org'

gem 'rspec'

gem 'activesupport'

gem 'lda-ruby'

gem 'google-translate'

gem 'nokogiri'

gem 'htmlentities' 

gem 'pry'

gem 'elasticsearch'

gem 'rake'

gem 'measurable'

gem 'text'
